# Generated by Django 3.2.9 on 2021-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
